### ISSUE TITLE
Sorry, that page does not exist - When running ebooks.py

### ISSUE THREAD

**Issue by stellasoft-jim** [tommeagher/heroku_ebooks#12]
When I run ebooks.py with DEBUG set to true, and 3 twitter accounts in source - i recieve this error.
It is successfully authenticating but failing to find...somewhere?
I don't know enough python to work it out.

**Comment by tommeagher** [comment]
Jim, did you figure this out?

**Comment by stellasoft-jim** [comment]
Hey - it turned out to be related to the "Less than 3600 tweets" issue - when I removed two of the accounts and added one that has 76k it worked - when I added the other two in any combination I would recieve this error.
So ultimately, user error rather than code :)
Thanks for responding.

**Comment by tommeagher** [comment]
Ahhh, that makes sense. I've been wanting to go back and fix that so it supports smaller accounts. This will help me prioritize that issue.
Glad this is helpful.

**Comment by stellasoft-jim** [comment]
Yeah - i'm gonna take a look and try and re-write myself so I understand what it does but it definitely seems related to that issue.
