### ISSUE TITLE
Trouble with buildpack/remote? 

### ISSUE THREAD

**Issue by joshuazaneweiss** [tommeagher/heroku_ebooks#16]
error read as follows, despite closely following directions (and as far as I can tell, adding the buildpack correctly through heroku): 

remote: Building source:
remote: 
remote: -----> Failed to detect set buildpack https://github.com/bear/python-twitter
remote: More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !   Push rejected to
 !  [remote rejected] master -> master (pre-receive hook declined)

any help (even just pointing me in the right direction to sort it out on my own) would be much appreciated, I'm a bit of a novice here.

**Comment by joshuazaneweiss** [comment]
(I double checked the buildpack was present, both through terminal and the heroku site)

**Comment by tommeagher** [comment]
I haven't seen this problem before. Did you try [this command in the terminal](https://devcenter.heroku.com/articles/buildpacks#setting-a-buildpack-on-an-application)? 
```heroku buildpacks:set heroku/python```
