### ISSUE TITLE
[ISSUE] Syntax Error

### ISSUE THREAD

**Issue by rtd62** [tommeagher/heroku_ebooks#17]
After pushing the files to the master app on Heroku and running "worker", I get these two errors:

`Running worker on ⬢ secret-taiga-39619... up, run.2390
Traceback (most recent call last):
  File "ebooks.py", line 7, in <module>
    from local_settings import *
  File "/app/local_settings.py", line 12
    SOURCE_ACCOUNTS = [“frontend_bot”]
                       ^
SyntaxError: invalid syntax`

**Comment by tommeagher** [comment]
This is very odd. Were you able to resolve this issue?
I have two theories:
* Could it be that you didn't close the quote at the end of line 9, after your Access Token Secret? That might throw this kind of error appearing on the next line. This is mentioned in this [StackOverflow thread](https://stackoverflow.com/questions/24237111/syntax-error-invalid-syntax-for-no-apparent-reason).
* Are you using smart quotes around "frontend_bot" in the list? Can you replace them with normal, straight quotes and try it? It's mentioned in this [StackOverflow thread](https://stackoverflow.com/questions/22917329/python-script-invalid-character), though I think that might give a different SyntaxError description.

**Comment by Furgersen7** [comment]
I am having the same issue with syntax as well. When I run my worker I get these errors:

`Traceback (most recent call last):
  File "ebooks.py", line 7, in <module>
    from local_settings import *
  File "/app/local_settings.py", line 11
SyntaxError: Non-ASCII character '\xe2' in file /app/local_settings.py on line 11, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

**Comment by tommeagher** [comment]
Hi @Furgersen7, if [this StackOverflow thread](https://stackoverflow.com/questions/21639275/python-syntaxerror-non-ascii-character-xe2-in-file) is accurate, it seems you might have introduced a stray byte in your local_settings.py somehow. Here's [a promising solution](https://stackoverflow.com/questions/21639275/python-syntaxerror-non-ascii-character-xe2-in-file#comment32703265_21639459). Do you want to try it?

**Comment by mackmo** [comment]
I am also having this issue, and have tried all the solutions posed on StackOverflow. Any suggestions?

**Comment by tommeagher** [comment]
@mackmo, so you're certain you're not using smartquotes inadvertently? What kind of text editor are you using?

**Comment by mackmo** [comment]
I'm using Mac's TextEdit program. All smart options are off,  and I've run it through [this diacritics remover](http://utils.paranoiaworks.org/diacriticsremover/) with no issues, but it still won't run.

**Comment by tommeagher** [comment]
What error message you getting, @mackmo?

**Comment by mackmo** [comment]
Here's the message:
`Traceback (most recent call last):
  File "ebooks.py", line 7, in <module>
    from local_settings import *
  File "/app/local_settings.py", line 7
SyntaxError: Non-ASCII character '\xe2' in file /app/local_settings.py on line 7, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
`

**Comment by tommeagher** [comment]
@mackmo I don't know much about TextEdit. You should try something like TextWrangler. With that, you can turn on View>Text Display>Show Invisibles to see that extra character that snuck in there.

**Comment by mackmo** [comment]
Thanks! Problem solved, I'll stick to TextWrangler from now on.

**Comment by tommeagher** [comment]
@mackmo 👍🏼
