### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by joelcava96** [tommeagher/heroku_ebooks#22]
sorry, i have no idea of what i have to do with this
Running worker on ⬢ lit-bayou-19362... up, run.6460 (Free)
Traceback (most recent call last):
  File "ebooks.py", line 7, in <module>
    from local_settings import *
  File "/app/local_settings.py", line 11
SyntaxError: Non-ASCII character '\xe2' in file /app/local_settings.py on line 11, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by tommeagher** [comment]
Hi @joelcava96. I think this is the same problem as #17. It seems some stray invisible characters snuck in your settings file somehow. Can you try [the solutions here](https://github.com/tommeagher/heroku_ebooks/issues/17#issuecomment-280085699) and see if those work?
I'm going to close this issue as a duplicate, but if it doesn't work, feel free to report back in issue #17.
