### ISSUE TITLE
Error fetching tweets from Twitter. Aborting.

### ISSUE THREAD

**Issue by XenonFiber** [tommeagher/heroku_ebooks#25]
I definitely have tweets on my source account and I double checked my API keys. Any clue what's going wrong?

![error](https://cloud.githubusercontent.com/assets/28912578/26433139/7601d48c-40c6-11e7-91a1-66389ae1bd55.png)

**Comment by tommeagher** [comment]
@XenonFiber sorry for the delayed reply. I'm not certain what is going on here. Is this the source account you're trying to use? https://twitter.com/xenonfiber

**Comment by XenonFiber** [comment]
Yup.

**Comment by XenonFiber** [comment]
I just tested the command again, and for some reason, it worked. Probably was just something wrong on Twitter's end, but reopen this if you need to.

**Comment by tommeagher** [comment]
@XenonFiber thanks for following up on this, 'cause I was stumped. If it acts up again, I can investigate.

**Comment by Casuallynoted** [comment]
Having a similar issue with mine, to my knowledge it's been configured entirely correctly.
![Screen Shot 2019-03-27 at 7 24 27 PM](https://user-images.githubusercontent.com/6272557/55118796-f32b6e80-50c5-11e9-9c50-0544e266e4e1.png)

**Comment by tommeagher** [comment]
@casuallynoted, can you give it, say, 12 hours and try again? I’m guessing this may have been an issue with the Twitter API at the time you tried this.

**Comment by Casuallynoted** [comment]
> @Casuallynoted, can you give it, say, 12 hours and try again? I’m guessing this may have been an issue with the Twitter API at the time you tried this.

Absolutely! Just tried it again but sadly getting the same issue.

**Comment by Casuallynoted** [comment]
Any chance this issue might be fixed? Tried running again but it gives me the same issue again :0

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tommeagher** [comment]
I'm at a loss. I'll have to look into this, but I'm not sure when I'll have an answer to this.

**Comment by tommeagher** [comment]
Archiving this repo and closing this issue as `WONTFIX`
