### ISSUE TITLE
Every Tweet is too similar

### ISSUE THREAD

**Issue by pit27** [tommeagher/heroku_ebooks#30]
Whenever I type "heroku run worker" everything works fine yet it always says "TOO SIMILAR: <tweet>". It happens 100% of the time. I have created other bots using this exact code and it works fine. I have no idea what is different. The account being posted to is completely empty

UPDATE: it fixed itself. no idea what happened

**Comment by tommeagher** [comment]
@pit27 glad this worked out. Thanks!
