### ISSUE TITLE
Stripping newlines from the source tweets results in words being joined together

### ISSUE THREAD

**Issue by 00dani** [tommeagher/heroku_ebooks#35]
So you get messy tweets like [this one](https://twitter.com/00d4n1_ebooks/status/910399752336011264). I think instead of stripping newlines, all consecutive "runs" of whitespace (newlines, tabs, and spaces) should be collapsed to single spaces. Then the original meaning of the tweets is preserved and passed into the Markov generator, but spurious whitespace is avoided.

This can be achieved with something like
```python
tweet.text = re.sub('\s+', ' ', tweet.text)
```
I've made it an issue rather than jut doing it as a pull req since it might be worth discussing first.

**Comment by tommeagher** [comment]
@00dani This seems like a good idea to me. Would \s+ catch \t and \n too?

**Comment by 00dani** [comment]
Yep, `\s` in regular expressions matches all whitespace characters. 👌

**Comment by tommeagher** [comment]
Cool, do you want to take a crack at a PR for this?
