### ISSUE TITLE
Add filtering to static sources

### ISSUE THREAD

**Issue by kmuncie** [tommeagher/heroku_ebooks#46]
Because of the Twitter API limits and my source accounts being over 40,000 tweets I have ended up combining the archives of my source accounts into one large CSV. I wish that static sources were treated as a first class source instead only treating it as a testing source.

**The main issue** I have encountered is that [`filter_status`](https://github.com/tommeagher/heroku_ebooks/blob/master/ebooks.py#L52) is not being run on static sources which is resulting in some awkward @'s. Could each string from static sources be run through `filter_status` the same as API tweets and toots?

I have little experience with Python but I am happy to take a stab at a PR if that is preferred.

Thanks

**Comment by tommeagher** [comment]
This is a great idea and a use case that I had not considered. I'd definitely be open to a PR if you want to give it a shot.

**Comment by TimLChan** [comment]
I think you can just change
`source_statuses += item.split(",")`
to
`source_statuses += filter_status(item.split(","))`

Or alternatively, just run `filter_status` after `ebook_status` [is generated](https://github.com/tommeagher/heroku_ebooks/blob/3dfd3c1715e6c31d9f7fc4933451c7cb11c881fc/ebooks.py#L203)

https://github.com/tommeagher/heroku_ebooks/blob/master/ebooks.py#L150-L151

**Comment by tommeagher** [comment]
Archiving this repo and closing this issue as `WONTFIX`
