### ISSUE TITLE
No statuses found!

### ISSUE THREAD

**Issue by ge0metrics** [tommeagher/heroku_ebooks#47]
I've tried multiple twitter accounts both with more than 3,600 tweets and less than that. Nothing works, it always produces "No statuses found!" message. I've run "heroku run worker" many times, and every single time it fails with this message.

http://prntscr.com/ind2nv

**Comment by ge0metrics** [comment]
after squinting at the code for half an hour I realised I wasn't putting the twitter usernames in the right place. [facepalm]

**Comment by tommeagher** [comment]
I've done the same thing many a time. Glad it worked out.
