### ISSUE TITLE
Do we need start and end quotes? Are there many hanging quotes?

### ISSUE THREAD

**Issue by tommeagher** [tommeagher/heroku_ebooks#5]

**Comment by rtd62** [comment]
I figure that quotes are necessary either way. I would just keep them in the code as-is. I code in CSS all day long, so quotes are needed all day long. 😆

**Comment by tommeagher** [comment]
Thanks, @rtd62. What I meant was that in the early days, I was noticing some tweets being created that would start a quotation but then would end abruptly. It somewhat depends on how often the source account uses quotes, but since no one's complained about the behavior, and I hardly ever see it, I'm not going to worry about it. Will close this issue. If anyone spots this happening regularly and wants to address it, I'm happy to re-open or to accept pull requests.

**Comment by tommeagher** [comment]
Here's an example: https://twitter.com/adriennelaf_ebx/status/772495811372539904
