### ISSUE TITLE
no statuses found!

### ISSUE THREAD

**Issue by perryimo** [tommeagher/heroku_ebooks#56]
<img width="535" alt="screen shot 2018-10-18 at 8 01 48 pm" src="https://user-images.githubusercontent.com/44279222/47190673-aff7f300-d310-11e8-9736-5bb7f7463ab6.png">

getting this error whenever I run the heroku run worker command. source account has near 10k tweets. I followed the code correctly, all that. what can I do to fix this?

thank you!

**Comment by perryimo** [comment]
<img width="745" alt="screen shot 2018-10-18 at 11 05 50 pm" src="https://user-images.githubusercontent.com/44279222/47195541-60bebc00-d32a-11e8-8ebb-65c4cbc35b2f.png">

here is what my code is looking like for reference (cropped out keys)

**Comment by tommeagher** [comment]
hi @perryimo. It looks like our local_settings.py has an extra line that we'll remove. You should put "perryimo" in the TWITTER_SOURCE_ACCOUNTS instead of SOURCE_ACCOUNTS and give it a try. That should resolve it.

**Comment by perryimo** [comment]
<img width="563" alt="screen shot 2018-10-19 at 5 45 45 pm" src="https://user-images.githubusercontent.com/44279222/47245329-d8dabf80-d3c6-11e8-99fd-da482d9e1ab7.png">

followed your instructions, now I am getting this error. It references the ebooks file, which I have (and have not touched), but I cannot find the others that it references. Maybe I am misinterpreting the error message...?

**Comment by tommeagher** [comment]
It’s a little hard to tell but it appears that your API keys aren’t being recognized. Did you generate the appropriate keys as in step 3 in the README? Did you add them to Heroku as environment variables like in step 13?

**Comment by perryimo** [comment]
<img width="736" alt="screen shot 2018-10-19 at 6 03 54 pm" src="https://user-images.githubusercontent.com/44279222/47245982-89e25980-d3c9-11e8-83d3-ca22678bac82.png">

I made sure that the keys are entered in on the correct line on the local_settings.py part, but did I enter them correctly (i.e. do I need to delete the parenthesis or quotation marks or...?)

Not sure if sharing the keys here is frowned upon or anything, which is why I marked them out.

Also, when I type heroku config, it shows me my keys and they are correct according to that as well. I am sure there's some minor detail I am missing, I just can't figure it out!

seriously thanks for the help so far.

**Comment by tommeagher** [comment]
Ahhhh. You shouldn’t edit that part of local_settings.py. You don’t want to put your actual keys in there because you don’t want to keep them in version control. 
Revert those lines back how they are in the repo: 
https://github.com/tommeagher/heroku_ebooks/blob/master/local_settings.py#L10-L13

This way, it’ll just look in your Heroku config for environment variables that match these variable names. That should sort you out.

**Comment by perryimo** [comment]
that did the trick! thanks again for all your help, I really appreciate it.
