### ISSUE TITLE
Twittereater is literally eating the CSV

### ISSUE THREAD

**Issue by lukethighwalker** [tommeagher/heroku_ebooks#59]
I have python 3.7, the latest version of git and everything. Working on windows 10. I try running the twittereater in git bash, and I get this:

```
Traceback (most recent call last): 
 File "twittereater.py", line 8, in <module>
    next(reader) #get rid of the twitter header
  File "C:\Users\micha\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 775: character maps to <undefined>
```
Furthermore, I have looked on other forums for resolutions, and entering `encoding="utf8"` on line 11 of twittereater.py, but this has resulted in nothing but creating a corrupt looking python file which resembles local_settings with error artifacts everywhere, and wiping the CSV file I was trying to make in to a corpus totally clean. 

I am new at this all, so I hope I explained the issue clearly. I have been successful in getting a bot working from these files and having the app sweep my existing recent tweets, however I feel the fun will compound if I can add my twitter archive (stretching back to 2011) to the mix. 

Thanks!

**Comment by tommeagher** [comment]
That piece was contributed by @TimLChan, and I haven't used it that much personally. Perhaps he can suggest what might be going awry here.

**Comment by TimLChan** [comment]
Do you mind changing the line to the below and seeing if it works? 
`f = open(TWITTER_ARCHIVE_NAME, 'r', encoding='utf8', errors='ignore')`

Furthermore, just checking your twitter archive is named tweets.csv?

**Comment by lukethighwalker** [comment]
@TimLChan Thank you for replying and asking. To verify, yes, I do have the archive named tweets.csv

The change suggested above did allow the process run to a certain extent- I now have a file in my Heroku_ebooks-master folder named ".txt", which has imported around 11 tweets in to a row of comma separated values, (it also seems to be pulling in retweets and hyperlinks, but I can get around those if we get this to work)

with your change, twittereater.py in Git Bash returned this error:

`Traceback (most recent call last):
  File "twittereater.py", line 15, in <module>
    tweetarchive.write("'%s'," % (row[5]))
  File "C:\Users\micha\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-40: character maps to <undefined>`

Thank you again for your continuing advice on this.

**Comment by TimLChan** [comment]
Looks like Windows is setting encoding as cp-1252

Try changing the writing line to the below 
`tweetarchive = open(TEST_SOURCE, 'w', encoding='utf8')`

Hyperlinks _should_ be imported as well, since the main app filters them out (pending #46)

**Comment by lukethighwalker** [comment]
[yay.txt](https://github.com/tommeagher/heroku_ebooks/files/3109993/yay.txt)
That seemed to do the trick! I have my text file now. Is there a way in Local_settings.py where I can make the app search my existing timeline and my archive file? or is it simply one or the other?

Thank you for all your help

**Comment by TimLChan** [comment]
> Is there a way in Local_settings.py where I can make the app search my existing timeline and my archive file? or is it simply one or the other?

Probably a question for @tommeagher 
I initially had an idea to auto update the corpus using Twitter's API, but after their API changes happened, I haven't looked in detail

**Comment by tommeagher** [comment]
@lukethighwalker this is a good idea that I haven't had a need for yet, but shouldn't be that difficult to implement. I'll open an issue for it in case someone would like to give it a try and send a pull request.

Thanks to @timlchan for troubleshooting this issue!
