### ISSUE TITLE
Drops input before newlines

### ISSUE THREAD

**Issue by elplatt** [tommeagher/heroku_ebooks#63]
It looks like the script sometimes generates multiline output but only outputs the final line. Is this expected behavior or a bug?
<img width="326" alt="Screen Shot 2019-06-19 at 2 52 50 PM" src="https://user-images.githubusercontent.com/308312/59792352-f63b9280-92a1-11e9-83df-1b2aca0594ef.png">
<img width="411" alt="Screen Shot 2019-06-19 at 2 53 34 PM" src="https://user-images.githubusercontent.com/308312/59792380-08b5cc00-92a2-11e9-9994-4f12a519dda7.png">

**Comment by tommeagher** [comment]
Archiving this repo and closing this issue as `WONTFIX`
