### ISSUE TITLE
Drop attribution?

### ISSUE THREAD

**Issue by tommeagher** [tommeagher/heroku_ebooks#7]
Chop off any tail ends that say ', via' or ', says' or whatever. But then check to see if the whole tweet comes verbatim from any tweet in the corpus.

**Comment by wrnb** [comment]
Hi Tom! I know it's been a while but I'm wondering if this is something you could revisit?

**Comment by tommeagher** [comment]
Hi! I can't promise I'll get to this in the near future, but I will accept pull requests if anyone wants to take a stab at this.

**Comment by sparky005** [comment]
Hey @tommeagher I just submitted #20 to try and resolve this issue. Please take a look and let me know what you think. Thanks!

**Comment by tommeagher** [comment]
Closed by 0ca5fa6, thanks to @sparky005.
