### ISSUE TITLE
Configuration for Markov Chain

### ISSUE THREAD

**Issue by actualguy** [tommeagher/heroku_ebooks#70]
A lot of my generated tweets are coming out quite short. Are there any variables within the Markov.py that can be tweaked to produce different outcomes or is it pretty set in stone?

**Comment by tommeagher** [comment]
You can try tinkering with the ORDER variable in the settings: https://github.com/tommeagher/heroku_ebooks#configuring Do your source tweets tend to be short as well?

**Comment by actualguy** [comment]
One of my source accounts does tweet somewhat short tweets, so I think I will take that out of the rotation. Switching between 2-4 didn't seem to have too much effect, but I will keep experimenting.


Thanks!

**Comment by tommeagher** [comment]
Cool. I'm guessing it's a matter of using short tweets as the source. Longer tweets, closer to the 280 limit, should return longer strings. Will close this for now, but feel free to reopen it if you want to discuss further as you experiment.
