### ISSUE TITLE
Api.py Running into Authentication Error to GetUser from Twitter

### ISSUE THREAD

**Issue by FTWDex** [tommeagher/heroku_ebooks#73]
I'm fairly new to python and Twitter API development, so this is likely something simple I am missing. I double and triple checked the documentation so I believe I have all of the keys and tokens setup correctly in both local_settings.py and in Heroku. 

On heroku run worker I see the following log:

 File "ebooks.py", line 161, in <module>
    handle_stats = api.GetUser(screen_name=user)
  File "/app/.heroku/python/lib/python3.7/site-packages/twitter/api.py", line 2868, in GetUser
    resp = self._RequestUrl(url, 'GET', data=parameters)
  File "/app/.heroku/python/lib/python3.7/site-packages/twitter/api.py", line 4959, in _RequestUrl
    raise TwitterError("The twitter.Api instance must be authenticated.")
twitter.error.TwitterError: The twitter.Api instance must be authenticated.

Twitter Dev dash looks like it has changed since docs, so I setup OAuth1.0a as that seemed closest to what was described. Is there something I may have missed? Should I be using a different setup on Twitter Dev?

Thanks in advance.

**Comment by tommeagher** [comment]
Hey, @FTWDex thanks for flagging this. I honestly haven't looked at the twitter API in forever. I'm not sure if this is a permissions issue, or if the Twitter library this script uses is really, really ancient. I'll try to look at it when I can, but I'm hoping another user who is more up to date on this might be able to help.

**Comment by tommeagher** [comment]
Archiving this repo and closing this issue as `WONTFIX`
