### ISSUE TITLE
Heroku ending free plans

### ISSUE THREAD

**Issue by tommeagher** [tommeagher/heroku_ebooks#75]
Today's [news from Heroku](https://blog.heroku.com/next-chapter) means that it will no longer allow free dynos, the kind that this repo relies on. I'm not sure yet if it's worth the effort to redesign this app for another platform, nor do I really have the time to support such an effort. 

What do you all think? Would you be willing to pay for a $7/month Heroku dyno to keep your ebooks account going? Or should we let this app die with dignity after 9 years? What would you want to see happen?

**Comment by lucymhdavies** [comment]
I'm migrating mine over to my personal Nomad cluster.

But... That's a very niche platform; I do not expect many folks have one of those.

I don't know what a free equivalent to Heroku would even be tbh. AWS Lambda free tier? Google Cloud Functions? Who knows.

**Comment by tommeagher** [comment]
Given the changes to Twitter's API in the last year, as well as Heroku's price changes, the ecosystem that this app was built on has eroded significantly since it first launched more than a decade ago. I don't have the bandwidth to support development of an app that is less powerful than it used to be. I believe that this will continue to run if you want to use it for Mastodon. I'm sure with a little elbow grease someone could get it running on BlueSky as well. I'm going to archive this repo. 

If anyone would like to take on the project, please fork it. Send me an email at hello [at] tommeagher [dot] com, and I can update the README to point people toward your new version. Thanks to all who have used and enjoyed this over the years. It was a real kick for me to see others put it to good use.
